# Copy pipeline-secrets-example.yml to pipeline-secrets.yml and update with your values then run:
# fly -t ci set-pipeline -p maven-cf-simple -c pipeline.yml -l pipeline-secrets.yml
---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/patrickcrocker/concourse-maven-cf-simple.git
    branch: master

- name: cf
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    #skip_cert_check: true

jobs:
- name: build
  public: true
  plan:
  - get: source-code
    trigger: true
  - task: build
    file: source-code/ci/build.yml
  - put: cf
    params:
      manifest: source-code/manifest.yml
      path: build-output/concourse-maven-cf-simple-0.0.1-SNAPSHOT.jar
